services:
  - type: web
    name: nolcop-shop-backend
    env: node
    rootDir: backend
    buildCommand: |
      npm install
      cd ../frontend && npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
    buildFilter:
      paths:
        - backend/**
        - frontend/**
    autoDeploy: true
